name: Build and Deploy Backend

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: latest
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      # Build & Push API Gateway
      - name: Build and Push Docker Image (API Gateway)
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/node-microservices-apigateway:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/node-microservices-apigateway:latest

      # Build & Push Identity Service
      - name: Build and Push Docker Image (Identity Service)
        uses: docker/build-push-action@v5
        with:
          context: ./identity-service
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/node-microservices-identity_service:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/node-microservices-identity_service:latest

      # Build & Push Post Service
      - name: Build and Push Docker Image (Post Service)
        uses: docker/build-push-action@v5
        with:
          context: ./post-service
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/node-microservices-post_service:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/node-microservices-post_service:latest

      # Build & Push Search Service
      - name: Build and Push Docker Image (Search Service)
        uses: docker/build-push-action@v5
        with:
          context: ./search-service
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/node-microservices-search_service:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/node-microservices-search_service:latest

      # Build & Push Media Service
      - name: Build and Push Docker Image (Media Service)
        uses: docker/build-push-action@v5
        with:
          context: ./media-service
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/node-microservices-media_service:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/node-microservices-media_service:latest
